path: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA
train: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA/images/train
val: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA/images/test2

names:
    0: Araba
    1: Insan
    2: UAP
    3: UAI
