path: /home/nurullah/Masaüstü/DENEME_DATA
train: /home/nurullah/Masaüstü/DENEME_DATA/images/train
val: /home/nurullah/Masaüstü/DENEME_DATA/images/test4
nc: 4
names:
  - Araba
  - Insan
  - UAP
  - UAI
