path: /home/nurullah/Masaüstü/DENEME_DATA
train: /home/nurullah/Masaüstü/DENEME_DATA/images/train5
val: /home/nurullah/Masaüstü/DENEME_DATA/images/train5
nc: 4
names:
  - Araba
  - Insan
  - UAP
  - UAI
