path: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA
train: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA/images/train
val: /home/nurullah/Masaüstü/NPC-AI/DENEME_DATA/images/test2
nc: 4
names:
  - Araba
  - Insan
  - UAP
  - UAI
