### DPVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 128
REMOVAL_WINDOW: 30
OPTIMIZATION_WINDOW: 25
PATCH_LIFETIME: 26

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0

# camera motion model
MOTION_MODEL: 'CONSTANT_VELOCITY'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: False

CENTROID_SEL_STRAT: 'EDGE_BIAS'
