name: hyz
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - torchvision=0.19.1
  - pytorch-scatter=2.1.2
  - pip:
    - python-decouple
    - requests>=2.31.0
    - pillow>=10.4.0
    - tqdm
    - tensorboard
    - numba
    - einops
    - pypose
    - kornia
    - numpy==1.26.4
    - plyfile
    - evo
    - opencv-python
    - yacs
    - ultralytics
    - scipy
    - scikit-learn
    - filterpy
    - pytest
    - git+https://github.com/cvg/LightGlue.git
